oidc:
  issuer-uri: https://dev-355680.okta.com/oauth2/default
  client-id: 0oabplyrfQc3dzkpE4x6
  client-secret: JoVUgRmSwRIIgeg7Hhea0QKJq_eAYug-KfW_cuXM

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-355680.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oabplyrfQc3dzkpE4x6
            client-secret: JoVUgRmSwRIIgeg7Hhea0QKJq_eAYug-KfW_cuXM
      resourceserver:
        jwt:
          issuer-uri: https://dev-355680.okta.com/oauth2/default
